import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { fmt12h } from "@muso/logic";
import { prettyDate, dateLabel, TYPE_LABELS } from "@/lib/labels";

/**
 * Word downloads for every document. Word-compatible HTML served as .doc —
 * opens in MS Word and Google Docs, fully editable (unlike the PDFs).
 * kinds: school-fp/<bookingId>, event/<bookingId>, birthday/<date>,
 *        memo/<date>, dept-brief/<date>?dept=<department>
 */

export const dynamic = "force-dynamic";

const esc = (v: unknown) =>
  String(v ?? "NA").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\n/g, "<br/>");

function kvTable(rows: [string, unknown][]): string {
  return `<table>${rows
    .map(([k, v]) => `<tr><td class="k">${esc(k)}</td><td>${esc(v)}</td></tr>`)
    .join("")}</table>`;
}

function grid(header: string[], rows: unknown[][]): string {
  return `<table><tr>${header.map((h) => `<th>${esc(h)}</th>`).join("")}</tr>${rows
    .map((r) => `<tr>${r.map((c) => `<td>${esc(c)}</td>`).join("")}</tr>`)
    .join("")}</table>`;
}

function wordDoc(title: string, body: string): NextResponse {
  const html = `<html xmlns:w="urn:schemas-microsoft-com:office:word"><head><meta charset="utf-8"><title>${esc(title)}</title>
<style>
  body { font-family: Calibri, Arial, sans-serif; font-size: 11pt; }
  h1 { font-size: 16pt; } h2 { font-size: 13pt; background: #FFFF99; padding: 4px; }
  table { border-collapse: collapse; width: 100%; margin-bottom: 12px; }
  td, th { border: 1px solid #999; padding: 4px 6px; vertical-align: top; }
  th { background: #EFEFEF; text-align: left; }
  td.k { width: 34%; font-weight: bold; background: #F5F5F5; }
</style></head><body><h1>${esc(title)}</h1>${body}
<p style="color:#888;font-size:9pt">Museum of Solutions (MuSo) | Generated by MuSo Ops Command Center</p>
</body></html>`;
  return new NextResponse(html, {
    headers: {
      "Content-Type": "application/msword",
      "Content-Disposition": `attachment; filename="${title.replace(/\W+/g, "_")}.doc"`,
    },
  });
}

const timeRow = (t: string | null | undefined) => (t ? fmt12h(t) : "NA");

export async function GET(req: Request, { params }: { params: { kind: string; key: string } }) {
  const supabase = createClient();
  const { kind, key } = params;
  const url = new URL(req.url);

  if (kind === "school-fp" || kind === "event") {
    const { data: b } = await supabase
      .from("bookings")
      .select("*, ops_poc:staff!bookings_ops_poc_id_fkey(name), sales_rep:staff!bookings_sales_rep_id_fkey(name)")
      .eq("id", key)
      .maybeSingle();
    if (!b) return NextResponse.json({ error: "Not found" }, { status: 404 });
    const date = prettyDate(b.visit_date);

    if (kind === "event") {
      const { data: asks } = await supabase
        .from("department_asks")
        .select("department, asks_text, status, poc:staff(name)")
        .eq("booking_id", key);
      return wordDoc(
        `Event FP ${b.name} ${b.visit_date}`,
        kvTable([
          ["Event Name", b.name],
          ["Event Date", date],
          ["Event Time", `${fmt12h(b.slot_start)} to ${fmt12h(b.slot_end)}`],
          ["Event Location", b.event_location],
          ["Type of Event", [b.is_ticketed ? "Ticketed" : "Free", b.partner_name ? `Collaboration (${b.partner_name})` : null].filter(Boolean).join(", ")],
          ["Ticket Price", b.is_ticketed ? `${b.ticket_price} (+ GST)` : "Free (RSVP)"],
          ["Ticketing Platform", b.ticketing_platform],
          ["MuSo PoC", b.ops_poc?.name],
          ["Partner PoC", b.partner_poc],
          ["Ideal Ages", b.ideal_ages],
          ["Expected Visitors", (b.children_planned ?? 0) + (b.adults_planned ?? 0)],
          ["About the Event", b.about_event],
          ["Setup (Internal)", b.setup_instructions_internal],
          ["Setup (External)", b.setup_instructions_external],
          ["Other Notes", b.other_notes],
        ]) +
          `<h2>Department Ops Asks</h2>` +
          grid(
            ["Department", "Ask", "POC", "Status"],
            (asks ?? []).map((a: any) => [a.department, a.asks_text, a.poc?.name, a.status])
          )
      );
    }

    // school-fp
    const { data: mp } = await supabase
      .from("movement_plans")
      .select("*, movement_plan_sessions(*, resource:resources(name)), movement_plan_tasks(*)")
      .eq("booking_id", key)
      .maybeSingle();
    let planHtml = "";
    if (mp) {
      const tasks = (mp.movement_plan_tasks ?? []).sort((a: any, b2: any) => a.sort_order - b2.sort_order);
      planHtml =
        `<h2>Movement Plan</h2>` +
        grid(["Task", "Timing", "Person(s)"], tasks.map((t: any) => [t.task, t.timing_text, t.person_names])) +
        grid(
          ["Session", "Timing", "Assignments"],
          [...new Set((mp.movement_plan_sessions ?? []).map((s: any) => s.session_number))].sort().map((num) => {
            const rows = (mp.movement_plan_sessions ?? []).filter((s: any) => s.session_number === num);
            return [
              `Session ${num}`,
              `${fmt12h(rows[0].from_time)} to ${fmt12h(rows[0].to_time)}`,
              rows.map((r: any) => `${r.resource?.name}: Group ${r.group_label} (${r.headcount})`).join(" | "),
            ];
          })
        );
    }
    const total = (b.children_planned ?? 0) + (b.teachers_planned ?? 0) + (b.escorts_planned ?? 0);
    return wordDoc(
      `School FP ${b.name} ${b.visit_date}`,
      kvTable([
        ["Date of Visit", date],
        ["Slot", `${fmt12h(b.slot_start)} to ${fmt12h(b.slot_end)}`],
        ["Booking Type", TYPE_LABELS[b.booking_type] ?? b.booking_type],
        ["Name of School", b.name],
        ["Location", b.location],
        ["POC from School", b.poc_external_name],
        ["Contact Number", b.poc_external_contact],
        ["POC from Operation", b.ops_poc?.name],
        ["No. of Students", b.children_planned],
        ["No. of Teachers", b.teachers_planned],
        ["No. of Escorts", b.escorts_planned],
        ["Total", total],
        ["No. of Buses", b.buses],
        ["Grade", b.grade],
        ["Sales Representative", b.sales_rep?.name],
        ["Travel Agent", b.travel_agent],
        ["POC from TA", b.poc_travel_agent],
        ["Bus Reporting Time", timeRow(b.bus_reporting_time)],
        ["Orientation Time", timeRow(b.orientation_time)],
        ["Kids Food", b.kids_menu],
        ["Kids Lunch Time", timeRow(b.kids_lunch_time)],
        ["Jain Kids", b.jain_kids || "NA"],
        ["Teachers Breakfast", timeRow(b.teachers_breakfast_time)],
        ["Teachers Lunch", b.teachers_menu],
        ["Food Vendor", b.food_vendor],
        ["Food Location", b.food_location],
        ["Exit Time", timeRow(b.exit_time)],
        ["Remarks", b.remarks],
      ]) + planHtml
    );
  }

  if (kind === "birthday") {
    const { data: bookings } = await supabase
      .from("bookings")
      .select("*")
      .eq("visit_date", key)
      .eq("booking_type", "birthday")
      .neq("status", "cancelled")
      .order("slot_start");
    if (!bookings?.length) return NextResponse.json({ error: "No birthday bookings" }, { status: 404 });
    const fields: [string, (b: any) => unknown][] = [
      ["Slot", (b) => `${fmt12h(b.slot_start)} - ${fmt12h(b.slot_end)}`],
      ["Host Name", (b) => b.name],
      ["Entry at Commons", (b) => timeRow(b.entry_commons_time)],
      ["Age Group", (b) => b.age_group],
      ["Entry Inside Museum", (b) => timeRow(b.entry_museum_time)],
      ["Cake Cutting & Food", (b) => (b.cake_cutting_start ? `${fmt12h(b.cake_cutting_start)} - ${fmt12h(b.cake_cutting_end)} (${b.cake_cutting_location ?? ""})` : "NA")],
      ["# Children", (b) => b.children_planned],
      ["# Adults", (b) => b.adults_planned],
      ["Total", (b) => (b.children_planned ?? 0) + (b.adults_planned ?? 0)],
      ["Decor", (b) => b.decor_type],
      ["F&B Menu", (b) => b.fnb_menu],
      ["Remark", (b) => b.remarks],
    ];
    return wordDoc(
      `Birthday FP ${key}`,
      grid(
        ["", ...bookings.map((_: any, i: number) => `${prettyDate(key)} (Slot ${i + 1})`)],
        fields.map(([label, fn]) => [label, ...bookings.map((b: any) => fn(b))])
      )
    );
  }

  if (kind === "memo") {
    const [{ data: bookings }, { data: pocs }, { data: counts }, { data: contacts }] = await Promise.all([
      supabase.from("bookings").select("*, ops_poc:staff!bookings_ops_poc_id_fkey(name)").eq("visit_date", key).neq("status", "cancelled").order("slot_start"),
      supabase.from("floor_poc_assignments").select("*").eq("visit_date", key).order("sort_order"),
      supabase.from("daily_visit_counts").select("*").eq("visit_date", key),
      supabase.from("staff").select("name, extension").not("extension", "is", null).eq("is_active", true),
    ]);
    return wordDoc(
      `Daily Memo ${key}`,
      `<h2>Today's Bookings</h2>` +
        grid(
          ["Type", "Name", "Timing", "Ops POC", "Total"],
          (bookings ?? []).map((b: any) => [
            TYPE_LABELS[b.booking_type] ?? b.booking_type,
            b.name,
            `${fmt12h(b.slot_start)} to ${fmt12h(b.slot_end)}`,
            b.ops_poc?.name,
            (b.children_planned ?? 0) + (b.adults_planned ?? 0) + (b.teachers_planned ?? 0) + (b.escorts_planned ?? 0) || "NA",
          ])
        ) +
        `<h2>Floor POCs</h2>` +
        grid(["Role", "Staff"], (pocs ?? []).map((p: any) => [p.floor_role, p.staff_names])) +
        `<h2>Ticketed Visitors</h2>` +
        grid(["Slot", "Children", "Adults"], (counts ?? []).map((c: any) => [c.slot_label === "Flexi Pass" ? "Flexi Pass" : fmt12h(c.slot_label), c.children, c.adults])) +
        `<h2>Contacts</h2>` +
        grid(["Name", "Extension"], (contacts ?? []).map((c: any) => [c.name, c.extension]))
    );
  }

  if (kind === "dept-brief") {
    const dept = url.searchParams.get("dept") ?? "housekeeping";
    const { data: asks } = await supabase
      .from("department_asks")
      .select("asks_text, status, department, poc:staff(name), booking:bookings!inner(name, visit_date, slot_start, slot_end)")
      .eq("booking.visit_date", key)
      .eq("department", dept);
    return wordDoc(
      `${dept} Brief ${key}`,
      `<p>${esc(dateLabel(key))}</p>` +
        grid(
          ["Booking", "Timing", "Ask", "POC", "Status"],
          (asks ?? []).map((a: any) => [
            a.booking.name,
            `${fmt12h(a.booking.slot_start)} to ${fmt12h(a.booking.slot_end)}`,
            a.asks_text,
            a.poc?.name,
            a.status,
          ])
        )
    );
  }

  return NextResponse.json({ error: "Unknown document kind" }, { status: 404 });
}
