import React from "react";
import { StyleSheet, Text, View } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: { padding: 28, fontSize: 9, fontFamily: "Helvetica", color: "#111" },
  h1: { fontSize: 14, fontFamily: "Helvetica-Bold", marginBottom: 8 },
  h2: { fontSize: 11, fontFamily: "Helvetica-Bold", marginTop: 10, marginBottom: 4 },
  row: { flexDirection: "row", borderBottomWidth: 0.5, borderColor: "#ccc" },
  cellLabel: { width: "38%", padding: 3, fontFamily: "Helvetica-Bold", backgroundColor: "#f5f5f5" },
  cellValue: { width: "62%", padding: 3 },
  band: { padding: 4, fontFamily: "Helvetica-Bold", textAlign: "center", marginTop: 4 },
  gridRow: { flexDirection: "row" },
  gridCell: { flex: 1, padding: 4, borderWidth: 0.5, borderColor: "#999", textAlign: "center" },
  footer: { position: "absolute", bottom: 16, left: 28, right: 28, fontSize: 7, color: "#888", textAlign: "center" },
});

export const na = (v: unknown): string =>
  v === null || v === undefined || v === "" ? "NA" : String(v);

export function KV({ label, value, valueBg }: { label: string; value: unknown; valueBg?: string }) {
  return (
    <View style={styles.row}>
      <Text style={styles.cellLabel}>{label}</Text>
      <Text style={[styles.cellValue, valueBg ? { backgroundColor: valueBg } : {}]}>{na(value)}</Text>
    </View>
  );
}

export function Footer() {
  return (
    <Text style={styles.footer} fixed>
      Museum of Solutions (MuSo) | JSW Foundation | Generated by MuSo Ops Command Center
    </Text>
  );
}
